### PR TITLE
Decorate each of the host actions with a can-do check

### LINKED ISSUE #46: Unconditional paramsRescan() crash
Surge XT Effects crashes if the host has not (yet) implemented clap_host_params:

Here, the call to paramsRescan() is unconditional:

https://github.com/free-audio/clap-juce-extensions/blob/dad123ef8a08e28e3b172bd5e9a45caa9c0be7a8/src/wrapper/clap-juce-wrapper.cpp#L274

### PR DESCRIPTION
**Pull request by baconpaul**
For instance, before _host.paramsRescan do a _host.canUseParams

Closes #46

### CODE REVIEW

**Comment by baconpaul** [comment]
@jatinchowdhury18 when you have a minute, if you could eyeball before I merge.

File: src/wrapper/clap-juce-wrapper.cpp [hunk 1]
```diff
@@ -212,7 +212,8 @@ class ClapJuceWrapper : public clap::helpers::Plugin<clap::helpers::Misbehaviour
                 if (isBeingDestroyed())
                     return;
 
-                _host.latencyChanged();
+                if (_host.canUseLatency())
```
Comment (jatinchowdhury18) [inline src/wrapper/clap-juce-wrapper.cpp:215]: I guess `_host.canFoo()` probably needs to be called on the main thread, otherwise it would be nice to avoid queueing an action for the main thread if we can't do the action anyway.

**Review by jatinchowdhury18 — APPROVED** [review]

File: src/wrapper/clap-juce-wrapper.cpp (hunk 1 above)
Comment (baconpaul) [reply src/wrapper/clap-juce-wrapper.cpp:215]: So the cans can in theory be called off the main thread but it sort of made me nervous to have a check which leads to an assert non-thread-aligned with the item. That said the plugin just checks a variable and its functions are set up in the candos.

I think it will be a rare case when these aren't implemented, so i did it this way. Also I wanted the code to read that every _host.foo has a _host.canfoo right next to it.

what do you think? I can go either way. Sort of 'edge case event suppression' vs 'clearer code when you copy and paste it' type thing?

Comment (jatinchowdhury18) [reply src/wrapper/clap-juce-wrapper.cpp:215]: Yeah, after thinking about it again, I think the way you currently have it is best, both in terms of thread-safety and readability :).
